# Generated by Django 5.1.5 on 2025-04-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='recommended_calories',
            field=models.PositiveSmallIntegerField(blank=True, default=2000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goal',
            field=models.SmallIntegerField(choices=[(-400, 'Weight loss'), (0, 'Weight maintenance'), (400, 'Weight gain')], default=0),
        ),
    ]
